config/routes.rb
SteamCardTracker::Application.routes.draw do

  admin_auth_routes

  namespace :admin do
    resources :games, only: [:index, :create, :update]
  end

  namespace :api do
    resources :games, only: [:index, :show] do
      get 'parse', on: :member
    end
  end

  get '/sitemap(.xml)' => 'home#sitemap', format: 'xml'

  root 'home#index'
end

app/models/admin.rb
class Admin
  include Mongoid::Document
  include Mongoid::Timestamps::Short

  field :e, as: :email, type: String
  field :p, as: :encrypted_password, type: String
end

app/models/daily_stats.rb
class DailyStats < ActiveRecord::Base
  attr_accessible :min_price_low_integer, :min_price_high_integer, :quantity_low, :quantity_high, :item

  belongs_to :item

  def min_price_low
    min_price_low_integer / 100
  end

  def min_price_low=(price)
    self.min_price_low_integer = price * 100
  end

  def min_price_high
    min_price_high_integer / 100
  end

  def min_price_high=(price)
    self.min_price_high_integer = price * 100
  end
end

app/models/game.rb
class Game
  include Mongoid::Document
  include Mongoid::Timestamps::Short

  field :n, as: :name, type: String
  field :ppb, as: :price_per_badge, type: Float

  has_many :items, dependent: :destroy

  validates :name, uniqueness: true

  default_scope -> { order_by(name: :asc) }

  def as_json(options = {})
    json_generator.generate
  end

  def as_full_json(options = {})
    json_generator.generate_full
  end

  def updated_today?
    updated_at.to_date == Time.now.utc.to_date if updated_at
  end

  private

  def json_generator
    @json_generator ||= GameJsonGenerator.new(self)
  end
end

app/models/item.rb
class Item
  include Mongoid::Document
  include Mongoid::Timestamps::Short

  field :n, as: :name, type: String
  field :l, as: :link_url, type: String
  field :i, as: :image_url, type: String

  belongs_to :game
  has_many :stats, dependent: :destroy

  def latest_price
    stats.last.min_price_low if stats.present?
  end

  def latest_quantity
    stats.last.quantity if stats.present?
  end

  def all_time_min_price_low
    stats.min(:min_price_low)
  end

  def all_time_min_price_high
    stats.max(:min_price_high)
  end

  def all_stats_data
    stats.map(&:data)
  end
end

app/models/stat.rb
class Stat
  include Mongoid::Document
  include Mongoid::Timestamps::Short

  field :l, as: :min_price_low, type: Float, default: 0
  field :h, as: :min_price_high, type: Float, default: 0
  field :q, as: :quantity, type: Integer, default: 0

  belongs_to :item

  default_scope -> { order_by(created_at: :asc) }

  def data
    [created_at_in_milliseconds, min_price_low, min_price_high, quantity]
  end

  private

  def created_at_in_milliseconds
    created_at.to_i * 1000
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_action :authenticate_admin!

  def index
    render :index, locals: { game: games_repository.new, games: games_repository.all }
  end

  def create
    if games_repository.find(game_params).blank?
      games_repository.create(game_params)
      flash[:success] = "#{game_params[:name]} has been created"
    else
      flash[:warning] = "#{game_params[:name]} is already in the database"
    end

    redirect_to admin_games_path
  end

  def update
    if game&.update_attributes(game_params)
      flash[:success] = "#{game_params[:name]} has been updated"
    else
      flash[:warning] = "#{game_params[:name]} has NOT been updated"
    end

    redirect_to admin_games_path
  end

  private

  def games_repository
    @games_repository ||= DefaultRepository.new(Game)
  end

  def game
    @game ||= games_repository.find(id: params[:id])
  end

  def game_params
    params.require(:game).permit(:name)
  end
end

app/controllers/api/games_controller.rb
class Api::GamesController < ApplicationController
  def index
    render json: games_repository.all.as_json
  end

  def show
    render json: game.as_full_json, status: :ok
  rescue => e
    render json: e.message, status: :unprocessable_entity
  end

  def parse
    updated_game = listings_parser(game).parse
    render json: updated_game.as_json, status: :ok
  rescue => e
    render json: e.message, status: :unprocessable_entity
  end

  private

  def games_repository
    @games_repository ||= DefaultRepository.new(Game)
  end

  def game
    @game ||= games_repository.find(id: params[:id])
  end

  def listings_parser(game)
    ListingsParser.new(game)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_login_path(locale = nil)
    admin_games_path
  end

  def after_logout_path(locale = nil)
    root_path
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    render :index, locals: { game: games_repository.new, games: games_repository.all }
  end

  def create
    games_repository.create(game_params)
    redirect_to games_path
  end

  private

  def games_repository
    @games_repository ||= DefaultRepository.new(Game)
  end

  def game_params
    params.require(:game).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :index
  end

  def sitemap
    render :sitemap, layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/games/index.haml
.admin.games
  #flash-messages
    - flash.each do |type, message|
      %div{ class: type }= message

  .header
    %h1
      Admin Panel
      = link_to admin_logout_path, class: "logout" do
        = icon('fas', 'sign-out-alt')

  %h2 Add a new game
  = form_for game, url: admin_games_path, method: :post do |f|
    = f.text_field :name, placeholder: 'New Game Title'
    = f.submit 'Save'

  %h2 Already in the database
  - games.each do |game|
    = form_for game, url: admin_game_path(game), method: :put do |f|
      .game
        %span.updated= "#{game.updated_at.to_date} | #{game.items.count.to_s.rjust(2, "0")} Items"
        = f.text_field :name
        = f.submit 'Update'

app/views/home/_game.haml
.game-title
  %span.collapse.toggle-game
    %span.name {{game.name}} ({{game.price_per_badge | currency}}/badge)
    %span.icon
      = icon('fas', 'angle-down')
      = icon('fas', 'angle-up', style: 'display: none')
  %span.reload-game= icon('fas', 'sync-alt')
  %span.updated-today{ 'ng-show' => 'game.updated_today' }= icon('fas', 'check')
  %span.time-to-load

.game-cards{ style: 'display:none' }
  .game-items
    .game-item{ 'ng-repeat' => 'item in game.items' }
      = render 'item'
  .game-chart

app/views/home/_item.haml
%a{ 'ng-href' => '{{item.link_url}}', target: :_blank }
  %img.left{ 'ng-src' => '{{item.image_url}}' }
  .right
    .name ({{item.latest_quantity}}) {{item.name | truncate}}
    .prices
      .low.success {{item.all_time_min_price_low | currency}}
      .current.info {{item.latest_price | currency}}
      .high.warning {{item.all_time_min_price_high | currency}}

app/views/home/index.haml
#steam-card-tracker{ 'ng-controller' => 'GamesController' }
  .header
    %span.app-title
      %span.left
        %span.name= "Steam Card Tracker"
        %input{ 'ng-model' => 'query', class: :search, placeholder: 'Filter games by name' }
      %span.right
        %span.sort-name{ 'ng-click' => "sort = 'name'" }= icon('fas', 'sort-alpha-down')
        %span.sort-price{ 'ng-click' => "sort = 'price_per_badge'" }= icon('fas', 'sort-numeric-down')
        %span.load-all-games= icon('fas', 'download')

  .games
    .game{ 'ng-repeat' => 'game in games | filter:query | orderBy:sort', id: '{{game.id}}' }
      = render 'game'

  .scroll-top
    = icon('fas', 'angle-double-up')

app/views/layouts/application.haml
!!!

%html
  %head
    %title Steam Card Tracker
    %meta{ name: :description, content: 'Track the historical prices of Steam trading cards.' }
    %meta{ name: :keywords, content: 'steam, steam market, trading, card, trading card, foil, booster, graph, trend, history, price, lowest price, current price' }
    %meta{ name: :viewport, content: 'width=device-width, initial-scale=1' }
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body{ 'ng-app' => 'cardtracker' }
    = yield